language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_FILE=cmake-3.5.2-Linux-x86_64.tar.gz
    - CMAKE_URL=http://www.cmake.org/files/v3.5/${CMAKE_FILE}

branches:
  only:
    - master

before_install:
  - mkdir -p ${DEPS_DIR}

install:
  - sed -i -e 's/gcov)/gcov-5)/g' CMakeLists.txt
  - wget ${CMAKE_URL} --quiet --no-check-certificate
  - mkdir -p cmake
  - tar -xzf ${CMAKE_FILE} -C cmake --strip-components 1
  - mv cmake ${DEPS_DIR}
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version
  - pip install --user gcovr

script:
  - CC=gcc-5 CXX=g++-5 FC=gfortran-5 COVERAGE=True cmake . -DCMAKE_BUILD_TYPE=Debug
  - make unittests
  - make coverage

after_success:
  - pushd coverage
  - bash <(curl -s https://codecov.io/bash) -X gcov
  - popd
