language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

branches:
  only:
    - master

install:
  - pip install --user conan
  - conan
  - conan --version

script:
  - conan install test -if build -s compiler=gcc -s compiler.version=5 -s compiler.libcxx=libstdc++11
  - CXX=g++-5 CV=gcov-5 cmake -H. -Bbuild -DCALCULATE_BUILD_TESTS=ON
  - cmake --build build --target make_test
  - cmake --build build --target test
  - cmake --build build --target coverage

after_success:
  - pushd build/cov/bin
  - bash <(curl -s https://codecov.io/bash) -x gcov
  - popd
