package:
  name: calculate
  version: "1.1.0dev2"

build:
  number: 1

source:
  path: ..

requirements:
  build:
    - python >=2.7
    - cffi >=1.0.0
    - vs2015_runtime # [win]
  run:
    - python >=2.7
    - cffi >=1.0.0
    - vs2015_runtime # [win]

about:
  license: MIT License
  home: https://github.com/newlawrence/Calculate
  summary: "Little math expression parser"
