package:
  name: calculate
  version: "1.2.2"

build:
  number: 1
  script: python setup.py install

source:
  path: ..

requirements:
  build:
    - python
    - cffi >=1.0.0
  run:
    - python
    - cffi >=1.0.0

about:
  license: MIT License
  home: https://github.com/newlawrence/Calculate
  summary: "Little math expression parser"
